# Create labeled ground truth data

In [2]:
import pandas as pd
requests_df = pd.read_csv('documents/Request-Response 1/request_1.csv')
requests_df.head()

,No.,Description,Quantity,Price,Per.,Amount,Min. Order,Good Thru.,Notes
0,1,"[CB] Corner Bead - paper faced, 10'",35288.66,NaN,"1,000 LF",NaN,NaN,NaN,NaN
1,2,"[T35820] 3-5/8"" 20ga Track, 10'",67703.01,NaN,"1,000 LF",NaN,NaN,NaN,NaN
2,3,"[S35820] 3-5/8"" 20ga Stud",235430.39,NaN,"1,000 LF",NaN,NaN,NaN,NaN
3,4,"[T35820SLOTTED] 3-5/8"" 20ga Slotted track, 10'",29362.03,NaN,"1,000 LF",NaN,NaN,NaN,NaN
4,5,"[X58] 5/8"" Firecode Core",1114504.66,NaN,"1,000 SF",NaN,NaN,NaN,NaN

In [3]:
responses_df = pd.read_csv('documents/Request-Response 1/response_1.csv')
responses_df.head()

,LINE,PRODUCT,Length,QTY,GAUGE,KSI,COAT,Length (FT),Weight (LB),PRICE,EXTENDED (USD)
0,1,37506,0',NaN,32DRY,33,GV,"35,289.00","3,183.42",176.00 MLF,"6,210.86"
1,2,264033,0',NaN,20EQ,50,G40EQ,"67,703.00","26,756.90",293.00 MLF,"19,836.98"
2,3,261033,0',NaN,20EQ,70,G40EQ,"235,430.00","99,271.41",295.00 MLF,"69,451.85"
3,4,76033,0',NaN,20DRY,33,G40,"29,362.00","25,471.83",810.00 MLF,"23,783.22"
4,5,264063,0',NaN,20EQ,50,G40EQ,"5,022.00","2,738.15",398.00 MLF,"1,998.76"

In [4]:
def get_customer_name(quantity: int):
    for index, row in requests_df.iterrows():
        if round(row['Quantity']) == quantity:
            return row['Description']

In [5]:
get_customer_name(35289)

"[CB] Corner Bead - paper faced, 10'"

In [6]:
product_nos = []
customer_names = []
for index, row in responses_df.iterrows():
    length_str = row['Length (FT)'].replace(',', '')
    length = round(float(length_str))
    customer_name = get_customer_name(length)
    product_nos.append(row['PRODUCT'])
    customer_names.append(customer_name)

In [7]:
# create df out of product_nos and customer_names
labels_df = pd.DataFrame(list(zip(customer_names, product_nos)), columns=['Customer Name', 'Product No'])
labels_df

                                        Customer Name  Product No
0                 [CB] Corner Bead - paper faced, 10'       37506
1                     [T35820] 3-5/8" 20ga Track, 10'      264033
2                           [S35820] 3-5/8" 20ga Stud      261033
3      [T35820SLOTTED] 3-5/8" 20ga Slotted track, 10'       76033
4                           [T620] 6" 20ga Track, 10'      264063
5                                 [S620] 6" 20ga Stud      261063
6                           [T620] 6" 20ga Track, 10'       76063
7                     [T15820] 1-5/8" 20ga Track, 10'      264013
8                           [S15820] 1-5/8" 20ga Stud      261013
9                     [T15820] 1-5/8" 20ga Track, 10'      266013
10                      [CH21220] 2-1/2" 20ga CH-Stud       43253
11                [JT21220] 2-1/2" 20ga J-Runner, 10'       94132
12                  [FS620] 6" 20 ga. Flat Stock, 10'       50063
13   [BDCHZ] Corner Bead Horizontal - paper faced, 8'       37506
14     [T35818SLOTTED] 3-5/8" 18ga Slotted Track, 10'       75035
15                    [T35818] 3-5/8" 18ga Track, 10'       80035
16                     [S35818] 3-5/8" 18ga Stud, 21'       15035
17                          [T618] 6" 18ga Track, 10'       80065
18                                [S618] 6" 18ga Stud       15065
19  [BLACKIRON] CRC Galv 1-1/2" 16 Ga Horizontal, 10'       30026
20         [T618CLG] 6" 18ga Track @ clg framing, 10'       80065
21              [S618CLG] 6" 18ga Stud @ ceilings, 8'       15065
22                            [CH620] 6" 20ga CH-Stud       43063
23                      [JT620] 6" 20ga J-Runner, 10'       94134
24           [T618SLOTTED] 6" 18ga Slotted Track, 10'       75065

In [8]:
labels_df.to_csv('documents/Request-Response 1/labels.csv', index=False)